services:
  - type: web
    name: telegram-github-bot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: GITHUB_PAT
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: TELEGRAM_ENABLE_POLLING
        value: "false"
    healthCheckPath: /health

